### ISSUE TITLE
Transferring data between Activities

### ISSUE THREAD

**Issue by farazfazli** [abk-chicago/ToDoList#2]
I see you had difficulty transferring data between Activities. I suggest you look into using the [Parceler](https://github.com/johncarl81/parceler) library for this purpose once you have more experience working with Java!

**Comment by abk-chicago** [comment]
Thank you for your suggestion.  I welcome all input. I am only on week 3 of Java. I will get there! :)

**Comment by farazfazli** [comment]
Great, be sure to check out #1! Good luck!
